# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - AITravelAPI

on:
  push:
    branches:
      - master # it's main branch in this project
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build with dotnet
        run: dotnet build WebApplication1/AITravel.sln --configuration Release

      - name: dotnet publish
        run: dotnet publish WebApplication1/AITravelAPI.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

      - name: Install EF Core CLI
        run: dotnet tool install --global dotnet-ef

      - name: Run EF Migrations on Azure SQL Database
        run: |
          dotnet ef database update --project Infrastructure --startup-project WebApplication1 --connection "Server=tcp:AITravelAPI-sql123.database.windows.net,1433;Initial Catalog=AITravelAPIDB;Persist Security Info=False;User ID=Gazureadmin;Password=${{ secrets.AZURE_SQL_PASSWORD }};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4DA74D5CE90C4C788A72B458D10C984F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9E70618E8BD34E9BAFE5098EABBF9B21 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7BE96AB1DA14493A97BC3CA059D11E4B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AITravelAPI'
          slot-name: 'Production'
          package: .
          
